/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package endpoints

import (
	"modulith-no-db/modules/cart/middleware"
	"modulith-no-db/shared/endpoints"
	"net/http"

	"github.com/gorilla/mux"
)

func GetItem(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	var db = middleware.GetDb(r.Context())
	var params = mux.Vars(r)

	var item, err = db.GetItemByItemId(ctx, params["itemId"])

	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
	} else {
		endpoints.JsonResponse(item, w)
	}
}

func GetItems(w http.ResponseWriter, r *http.Request) {
	var db = middleware.GetDb(r.Context())

	var items, err = db.GetItems(r.Context())
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
	} else {
		endpoints.JsonResponse(items, w)
	}
}
