/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package endpoints

import (
	"modulith/modules/cart/middleware"
	"modulith/shared/endpoints"
	"modulith/shared/getters"
	"net/http"

	"github.com/gorilla/mux"
)

func AddItemToCart(w http.ResponseWriter, r *http.Request) {
	var ctx = r.Context()
	var db = middleware.GetDb(ctx)
	var userId = getters.GetUserId(r)
	var params = mux.Vars(r)

	var item, err = db.GetItemByItemId(ctx, params["itemId"])
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
		return
	}

	cart, err := db.GetCartByUserId(ctx, userId)
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
		return
	}

	_, err = db.AddItemToCart(ctx, item.Id, cart)
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
		return
	}

	itemsIds, err := db.GetItemsIdsInCart(ctx, cart)
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
		return
	}

	items, err := db.GetItemsByIds(ctx, itemsIds)
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	endpoints.JsonResponse(items, w)
}

func RemoveItemFromCart(w http.ResponseWriter, r *http.Request) {
	var ctx = r.Context()
	var db = middleware.GetDb(ctx)
	var userId = getters.GetUserId(r)
	var params = mux.Vars(r)

	var item, err = db.GetItemByItemId(ctx, params["itemId"])
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
		return
	}

	cart, err := db.GetCartByUserId(ctx, userId)
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
		return
	}

	_, err = db.RemoveItemFromCart(ctx, item.Id, cart)
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
		return
	}

	itemsIds, err := db.GetItemsIdsInCart(ctx, cart)
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
		return
	}

	items, err := db.GetItemsByIds(ctx, itemsIds)
	if err != nil {
		endpoints.FailUnexpectedError(err, w, r)
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	endpoints.JsonResponse(items, w)
}
