/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package endpoints

import (
	"modulith/modules/invoice/middleware"
	"net/http"

	"github.com/gorilla/mux"
)

func GetInvoiceById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	var db = middleware.GetDb(r.Context())
	var params = mux.Vars(r)

	var invoice, err = db.GetInvoiceByInvoiceId(ctx, params["invoiceId"])

	if err != nil {
		failUnexpectedError(err, w, r)
	} else {
		jsonResponse(invoice, w)
	}
}

func GetInvoicePdfById(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
