/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package clients

import (
	"context"

	"microservices/modules/order/database"
	db "microservices/modules/order/database"
)

type OrderApi interface {
	GetOrderByOrderId(ctx context.Context, orderId string) (*database.Order, error)
}
type OrderApiService service

func (a *OrderApiService) GetOrderByOrderId(ctx context.Context, orderId string) (*db.Order, error) {
	url := a.client.cfg.BasePath + "/order/" + orderId

	var order = new(db.Order)

	var _, err = a.client.doCallHttp(ctx, url, "Get", nil, order)
	return order, err
}
