/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package clients

import (
	"context"
	"fmt"
	"microservices/modules/item/database"
	"strings"

	"github.com/AzinKhan/functools"
)

type ItemApi interface {
	GetItemByItemId(ctx context.Context, item_id string) (*database.Item, error)
	GetItems(ctx context.Context) ([]database.Item, error)
	GetItemsByIds(ctx context.Context, itemIds []int64) ([]database.Item, error)
}

type ItemApiService service

func (a *ItemApiService) GetItemByItemId(ctx context.Context, itemId string) (*database.Item, error) {
	url := a.client.cfg.BasePath + "/item/" + itemId

	var item = new(database.Item)

	var _, err = a.client.doCallHttp(ctx, url, "Get", nil, item)
	return item, err
}

func (a *ItemApiService) GetItems(ctx context.Context) ([]database.Item, error) {
	url := a.client.cfg.BasePath + "/item"

	var items []database.Item
	var _, err = a.client.doCallHttp(ctx, url, "Get", nil, items)

	return items, err
}

func (a *ItemApiService) GetItemsByIds(ctx context.Context, itemIds []int64) ([]database.Item, error) {
	var queryParam = strings.Join(functools.Map(func(id int64) string {
		return fmt.Sprintf("%d", id)
	}, itemIds), ",")

	url := a.client.cfg.BasePath + "/item?ids=" + queryParam

	var items []database.Item
	var _, err = a.client.doCallHttp(ctx, url, "Get", nil, items)
	return items, err
}
