/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package clients

import (
	"context"

	"microservices/modules/cart/database"
)

type CartApi interface {
	UpsertShoppingCart(ctx context.Context, user_id string) (*database.Cart, error)
	// AddItemToShoppingCart(ctx context.Context, itemId int64, cart *database.Cart) (*database.RelItemCart, error)
	// RemoveItemFromShoppingCart(ctx context.Context, itemId int64, cart *database.Cart) (*database.RelItemCart, error)
	GetItemIdsInShoppingCart(ctx context.Context, cart *database.Cart) ([]int64, error)
	RemoveShoppingCart(ctx context.Context, cart *database.Cart) (*database.Cart, error)
}

type CartApiService service

func (a *CartApiService) UpsertShoppingCart(ctx context.Context, userId string) (*database.Cart, error) {
	url := a.client.cfg.BasePath + "/cart/user/" + userId

	var cart = new(database.Cart)

	var _, err = a.client.doCallHttp(ctx, url, "Get", nil, cart)
	return cart, err
}

func (a *CartApiService) GetItemIdsInShoppingCart(ctx context.Context, cart *database.Cart) ([]int64, error) {
	url := a.client.cfg.BasePath + "/cart/" + cart.CartId.String() + "/item/id"

	var ids []int64

	var _, err = a.client.doCallHttp(ctx, url, "Get", nil, ids)

	return ids, err
}

func (a *CartApiService) RemoveShoppingCart(ctx context.Context, cart *database.Cart) (*database.Cart, error) {
	url := a.client.cfg.BasePath + "/cart/" + cart.CartId.String()

	var deletedCart = new(database.Cart)

	var _, err = a.client.doCallHttp(ctx, url, "Delete", nil, deletedCart)
	return deletedCart, err
}
