/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/uptrace/bun"
)

type Invoice struct {
	bun.BaseModel `bun:"table:invoice,alias:inv"`

	Id int64 `json:"-" bun:"id,pk,autoincrement"`

	InvoiceId uuid.UUID `json:"id,omitempty" bun:"type:uuid,default:uuid_generate_v4()"`

	OrderSeqId int64 `json:"-"`

	Price float64 `json:"price,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty" bun:"type:timestamp,default:now()"`
	// Invoice Status
	Status string `json:"status,omitempty"`

	PdfLink string `json:"pdfLink,omitempty"`
}
