/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/uptrace/bun"
)

type Order struct {
	bun.BaseModel `bun:"table:order,alias:o"`

	Id int64 `json:"-" bun:"id,pk,autoincrement"`

	OrderId uuid.UUID `json:"id,omitempty" bun:"type:uuid,default:uuid_generate_v4()"`

	Title string

	Description string

	Quantity int `json:"quantity,omitempty"`

	Price float64 `json:"price,omitempty"`

	ShipDate time.Time `json:"shipDate,omitempty"`
	// Order Status
	Status string `json:"status,omitempty"`

	Complete bool `json:"complete,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty" bun:"type:timestamp,default:now()"`
}
