/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/uptrace/bun"
)

type Payment struct {
	bun.BaseModel `bun:"table:payment,alias:p"`

	Id int64 `json:"-" bun:"id,pk,autoincrement"`

	InvoiceSeqId int64 `json:"-"`

	PaymentId uuid.UUID `json:"id" bun:"type:uuid,default:uuid_generate_v4()"`

	CreditCardNumber int64 `json:"creditCardNumber,omitempty"`

	Amount float64 `json:"amount,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty" bun:"type:timestamp,default:now()"`
}
