version: '3'

services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.70.0
    restart: on-failure
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml

  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modulith
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d modulith']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'

  server-modulith:
    build: "../../server-modulith/"
    environment:
      DATABASE_URI: postgres://postgres:postgres@postgres:5432/modulith?sslmode=disable
      UPTRACE_DSN: http://project2_secret_token@192.168.10.88:14317/2
      PORT: 8080
      MODE: invoice-client-server
      INVOICE_HOST: http://nginx:80
      VIRTUAL_PATH: "/"
      VIRTUAL_HOST: "localhost,nginx"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
        reservations:
          cpus: '0.5'
          memory: 20M
    ports:
      - 8082:8080
  server-invoice1:
    build: "../../server-modulith/"
    environment:
      DATABASE_URI: postgres://postgres:postgres@postgres:5432/modulith?sslmode=disable
      UPTRACE_DSN: http://project2_secret_token@192.168.10.88:14317/2
      PORT: 8080
      MODE: invoice-server
      INVOICE_HOST: http://nginx:80
      VIRTUAL_PATH: "~^/api/v1/invoice"
      VIRTUAL_HOST: "localhost,nginx"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
        reservations:
          cpus: '0.5'
          memory: 20M
    ports:
      - 8081:8080
  server-invoice2:
    build: "../../server-modulith/"
    environment:
      DATABASE_URI: postgres://postgres:postgres@postgres:5432/modulith?sslmode=disable
      UPTRACE_DSN: http://project2_secret_token@192.168.10.88:14317/2
      PORT: 8080
      MODE: invoice-server
      VIRTUAL_PATH: "~^/api/v1/invoice"
      VIRTUAL_HOST: "localhost,nginx"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
        reservations:
          cpus: '0.5'
          memory: 20M
    ports:
      - 8083:8080
  server-invoice3:
    build: "../../server-modulith/"
    environment:
      DATABASE_URI: postgres://postgres:postgres@postgres:5432/modulith?sslmode=disable
      UPTRACE_DSN: http://project2_secret_token@192.168.10.88:14317/2
      PORT: 8080
      MODE: invoice-server
      VIRTUAL_PATH: "~^/api/v1/invoice"
      VIRTUAL_HOST: "localhost,nginx"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
        reservations:
          cpus: '0.5'
          memory: 20M
    ports:
      - 8084:8080

  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./volumes/nginx/:/etc/nginx/conf.d/"
    ports:
      - 127.0.0.1:8080:80
      
