/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import (
	"time"
)

type Cart struct {
	Id string `json:"id,omitempty"`

	Items []Item `json:"items,omitempty"`

	TotalQuantity int32 `json:"totalQuantity,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
