/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type OrderOrderIdBody struct {
	CreditCardNumber int32 `json:"creditCardNumber,omitempty"`

	Amount float64 `json:"amount,omitempty"`
}
