/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a example for performance study based on the OpenAPI 3.0 specification.
 *
 * API version: 1.0.11
 * Contact: skalicky.martin@iotdomu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import (
	"time"
)

type Item struct {
	Id string `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`

	Price float64 `json:"price,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
